# Starter pipeline 
trigger: none

pool: Devops_Pipline
 
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    backendServiceArm: 'Federation_service_connection'
    backendAzureRmResourceGroupName: 'Rishi_RG'
    backendAzureRmStorageAccountName: 'storageaccount7211'
    backendAzureRmContainerName: 'terraformcontainer'
    backendAzureRmKey: 'dev.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    environmentServiceNameAzureRM: 'Federation_service_connection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent_Module'
    environmentServiceNameAzureRM: 'Federation_service_connection'
